import json
from pathlib import Path

Import("env")

project_dir = Path(env.subst("$PROJECT_DIR"))
source = project_dir / "config.example.json"
target = project_dir / "src" / "config_example_generated.h"

text = source.read_text(encoding="utf-8")
json.loads(text)

escaped = text.replace("\\", "\\\\").replace('"', '\\"').splitlines()
lines = [
    "#pragma once",
    "",
    "// Generated by scripts/generate_config_header.py from config.example.json.",
    "// Do not edit this file by hand.",
    "static constexpr const char *CONFIG_EXAMPLE_JSON =",
]
for line in escaped:
    lines.append(f'    "{line}\\n"')
lines[-1] += ";"
lines.append("")

target.write_text("\n".join(lines), encoding="utf-8")
