[env:t-sim7080g-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; =============================
; SERIAL
; =============================
monitor_speed = 115200
upload_speed = 921600
monitor_filters = time
upload_port  = COM5
monitor_port = COM5

; =============================
; BUILD FLAGS
; =============================
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DTINY_GSM_MODEM_SIM7080
    -DTINY_GSM_RX_BUFFER=1024
    -DXPOWERS_CHIP_AXP2101
    -DGV2_UART_RX_GPIO_CFG=16
    -DGV2_UART_TX_GPIO_CFG=17
    -DGV2_UART_BAUD_CFG=921600

    ; Keep serial output quiet unless explicitly debugging.
    -DCORE_DEBUG_LEVEL=0

; =============================
; FLASH / PARTITIONS
; =============================
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.psram = enabled

; =============================
; LIBRARIES (NONE YET)
; =============================
lib_deps =
    https://github.com/vshymanskyy/TinyGSM.git
    lewisxhe/XPowersLib
    bblanchon/ArduinoJson@^7.0.0
